
name: Setup Java and Maven
description: Sets up JDK 21 with Maven caching

inputs:
  java-version:
    description: The Java version to use
    required: false
    default: '21'

runs:
  using: composite
  steps:
    - name: Set up JDK ${{ inputs.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'temurin'
        cache: maven

